### ISSUE TITLE
FlyoutMenu throws ReferenceError: Element is not defined

### ISSUE THREAD

**Issue by hadnet** [carbon-design-system/carbon-addons-iot-react#1760]
### What package is this for?

- [ X] React

### Describe the bug

FllyoutMenu component throws this when I run yarn build in Next.js 9.5.5

> Build error occurred
```ts
ReferenceError: Element is not defined
    at Object.<anonymous> (/Users/jon/NextJs/project/node_modules/carbon-addons-iot-react/lib/src/components/List/ListItem/ListItem.jsx:50:35)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/jon/NextJs/project/node_modules/carbon-addons-iot-react/lib/src/components/List/List.jsx:32:18)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10) {
  type: 'ReferenceError'
}
error Command failed with exit code 1.
```

### To Reproduce

 error happens when building a project using Next.js (yarn build)

### Environment/versions:

- OS: [MacOS]
- Browser: [chrome, safari]
```json
"carbon-addons-iot-react": "^2.140.0"
```
### Additional context

Using Next.js v9.5.5

**Comment by tay1orjones** [comment]
Thanks for reporting this, we haven't done much SSR testing and would like to close gaps like this. I've got a fix incoming.
