### ISSUE TITLE
[repo] useDeepCompareEffect, dequal - RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1797]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

`useDeepCompareEffect` [does not support](https://github.com/kentcdodds/use-deep-compare-effect/issues/7) comparing props (or prop objects/arrays that contain props) of type Element or Node, `useDeepCompareEffect` is unable to compare them due to these including the entire (very large) React tree.

This presents as an error of the underlying comparison library within `useDeepCompareEffect`, `dequal` in both browser and/or tests:

```
RangeError: Maximum call stack size exceeded

      at dequal (node_modules/dequal/dist/index.js:9:16)
      at dequal (node_modules/dequal/dist/index.js:77:28)
      at dequal (node_modules/dequal/dist/index.js:77:28)
      at ...
```

One way to partially fix this is to stop blindly comparing huge prop objects, like `table.view` for instance, and instead compare the specific props within that are not of type Element or Node. I've submitted a PR for this for StatefulTable/Table https://github.com/carbon-design-system/carbon-addons-iot-react/pull/1782 but we have additional components that we need to investigate

- [x] [`CardRenderer.jsx`](https://github.com/carbon-design-system/carbon-addons-iot-react/blob/d63c51871be9006f698354af6821d5cbdb637294/src/components/Dashboard/CardRenderer.jsx#L31)
- [x] [`ImageHotspots.jsx`](https://github.com/carbon-design-system/carbon-addons-iot-react/blob/1644c8407ea05e7cdcb7900c91f847ba663a3904/src/components/ImageCard/ImageHotspots.jsx#L365)
- [x] [`HierarchyList.jsx`](https://github.com/carbon-design-system/carbon-addons-iot-react/blob/581e8e247530a6979354de727c6694285d0fd0b4/src/components/List/HierarchyList/HierarchyList.jsx#L209) (this is confirmed to be comparing Nodes within the `items` prop and is prone to this error)
- [x] [`TableHead.jsx`](https://github.com/carbon-design-system/carbon-addons-iot-react/blob/2aac0dc996a2f361cc05c0abcea87292a0c50b69/src/components/Table/TableHead/TableHead.jsx#L285)
- [x] [`StatefulTtileCatalog.jsx`](https://github.com/carbon-design-system/carbon-addons-iot-react/blob/1644c8407ea05e7cdcb7900c91f847ba663a3904/src/components/TileCatalog/StatefulTileCatalog.jsx#L39)
- [x] [`TimeSeriesCard.jsx`](https://github.com/carbon-design-system/carbon-addons-iot-react/blob/48f9a118e9e8d36e74ec0ecf2455afc93bff3b3c/src/components/TimeSeriesCard/TimeSeriesCard.jsx#L424)

This is just an initial list that will become outdated - search for usages of `useDeepCompareEffect` to find a current list.

### To Reproduce

This is only reproducible in environments with babel deps versions >=7.12.0, which is why we don't see the issue currently our own codebase/storybook.

### Expected behavior

[Deep comparison is an anti-pattern](https://twitter.com/dan_abramov/status/1104414272753487872). Most particularly with objects of unknown size like the nested structure of `items` for HierarchyList.

#### Ideal behavior:
- Components don't use `useDeepCompareEffect` 

#### Not ideal, but acceptable behavior:
- Components that absolutely require usage of `useDeepCompareEffect` depend on more specific sub props, do not compare Nodes or Elements, and thoroughly document why it's required and a normal `useEffect` doesn't work.

### Environment/versions:

- `carbon-addons-iot-react` version: 2.140.0

**Comment by tay1orjones** [comment]
To my knowledge the only workaround for consumers that run into this error is to regenerate the component via a `key` tied to the value of one/some of the props/state being deep compared.
