### ISSUE TITLE
[DashboardEditor]: Raise test coverage

### ISSUE THREAD

**Issue by kevinsperrine** [carbon-design-system/carbon-addons-iot-react#2152]
We must raise the test coverage for this component and remove the exceptions found in [jest.config.js](https://github.com/carbon-design-system/carbon-addons-iot-react/blob/next/packages/react/jest.config.js) file.

- [x] write test for DashboardEditor.jsx
- [x] remove exception from jest.config.js
- [x] update [epic](https://github.com/carbon-design-system/carbon-addons-iot-react/issues/707) to show this is complete

**Comment by kevinsperrine** [comment]
This one may have to wait....been fighting a lot of weird jsdom errors all day. I've tried fireEvent.click, userEvent.click, preventing it from bubbling, etc. Still get this error everytime and google/github searches aren't giving my anything. Even tried upgrading testing-library/jest/jsdom, etc. @davidicus you have any other ideas?

```js
onDragEnd called before onDragStart.

      392 |     });
      393 | 
    > 394 |     userEvent.click(screen.getByText('Add from gallery'));
          |               ^
      395 |     await waitFor(() => {
      396 |       expect(screen.getByText('Image gallery')).toBeVisible();
      397 |     });

      at Object.onStop (node_modules/react-grid-layout/build/GridItem.js:190:15)
      at DraggableCore.handleDragStop (node_modules/react-draggable/build/cjs/DraggableCore.js:275:40)
      at node_modules/react-draggable/build/cjs/DraggableCore.js:310:20
      at HTMLUnknownElement.callCallback (../../node_modules/react-dom/cjs/react-dom.development.js:336:14)
      at innerInvokeEventListeners (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:330:27)
      at invokeEventListeners (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:281:3)
      at HTMLUnknownElementImpl._dispatch (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:228:9)
      at HTMLUnknownElementImpl.dispatchEvent (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:101:17)
      at HTMLUnknownElement.dispatchEvent (../../node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:207:34)
      at Object.invokeGuardedCallbackDev (../../node_modules/react-dom/cjs/react-dom.development.js:385:16)
      at invokeGuardedCallback (../../node_modules/react-dom/cjs/react-dom.development.js:440:31)
      at invokeGuardedCallbackAndCatchFirstError (../../node_modules/react-dom/cjs/react-dom.development.js:454:25)
      at executeDispatch (../../node_modules/react-dom/cjs/react-dom.development.js:584:3)
      at executeDispatchesInOrder (../../node_modules/react-dom/cjs/react-dom.development.js:609:5)
      at executeDispatchesAndRelease (../../node_modules/react-dom/cjs/react-dom.development.js:713:5)
      at executeDispatchesAndReleaseTopLevel (../../node_modules/react-dom/cjs/react-dom.development.js:722:10)
      at forEachAccumulated (../../node_modules/react-dom/cjs/react-dom.development.js:694:8)
      at runEventsInBatch (../../node_modules/react-dom/cjs/react-dom.development.js:739:3)
      at runExtractedPluginEventsInBatch (../../node_modules/react-dom/cjs/react-dom.development.js:880:3)
      at handleTopLevel (../../node_modules/react-dom/cjs/react-dom.development.js:5803:5)
      at batchedEventUpdates$1 (../../node_modules/react-dom/cjs/react-dom.development.js:24401:12)
      at batchedEventUpdates (../../node_modules/react-dom/cjs/react-dom.development.js:1415:12)
      at dispatchEventForPluginEventSystem (../../node_modules/react-dom/cjs/react-dom.development.js:5894:5)
      at attemptToDispatchEvent (../../node_modules/react-dom/cjs/react-dom.development.js:6010:5)
      at dispatchEvent (../../node_modules/react-dom/cjs/react-dom.development.js:5914:19)
      at unstable_runWithPriority (../../node_modules/scheduler/cjs/scheduler.development.js:697:12)
      at runWithPriority$2 (../../node_modules/react-dom/cjs/react-dom.development.js:12149:10)
      at discreteUpdates$1 (../../node_modules/react-dom/cjs/react-dom.development.js:24417:12)
      at discreteUpdates (../../node_modules/react-dom/cjs/react-dom.development.js:1438:12)
      at dispatchDiscreteEvent (../../node_modules/react-dom/cjs/react-dom.development.js:5881:3)
      at innerInvokeEventListeners (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:330:27)
      at invokeEventListeners (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:281:3)
      at HTMLButtonElementImpl._dispatch (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:228:9)
      at HTMLButtonElementImpl.dispatchEvent (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:101:17)
      at HTMLButtonElement.dispatchEvent (../../node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:207:34)
      at ../../node_modules/@testing-library/dom/dist/events.js:25:20
      at ../../node_modules/@testing-library/react/dist/pure.js:64:16
      at batchedUpdates$1 (../../node_modules/react-dom/cjs/react-dom.development.js:24386:12)
      at act (../../node_modules/react-dom/cjs/react-dom-test-utils.development.js:1092:14)
      at Object.eventWrapper (../../node_modules/@testing-library/react/dist/pure.js:63:28)
      at fireEvent (../../node_modules/@testing-library/dom/dist/events.js:16:35)
      at Function.fireEvent.<computed> [as mouseUp] (../../node_modules/@testing-library/dom/dist/events.js:125:36)
      at clickElement (../../node_modules/@testing-library/user-event/dist/click.js:89:20)
      at Object.click (../../node_modules/@testing-library/user-event/dist/click.js:132:5)
      at _callee$ (src/components/DashboardEditor/DashboardEditor.test.jsx:394:15)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.<computed> [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
```
