### ISSUE TITLE
[SuiteHeader] javascript urls in links

### ISSUE THREAD

**Issue by kevinsperrine** [carbon-design-system/carbon-addons-iot-react#2450]
### What package is this for?

- [X] React
- [ ] Angular

### Describe the bug
While cleaning up testing output we've uncovered some other bugs that may introduce breaking changes that need to be fixed in v3.
```
  ● Console

    console.error
      Warning: A future version of React will block javascript: URLs as a security precaution. Use event handlers instead if you can. If you need to generate unsafe HTML try using dangerouslySetInnerHTML instead. React was passed "javascript:void(0)".
          in a (created by Link)
          in Link (created by ForwardRef(HeaderMenuItem))
          in li (created by ForwardRef(HeaderMenuItem))
          in ForwardRef(HeaderMenuItem) (created by HeaderActionMenu)
          in ul (created by HeaderActionMenu)
          in div (created by HeaderActionMenu)
          in HeaderActionMenu (created by ForwardRef)
          in ForwardRef (created by HeaderAction)
          in div (created by HeaderAction)
          in HeaderAction (created by HeaderActionGroup)
          in div (created by HeaderGlobalBar)
          in HeaderGlobalBar (created by HeaderActionGroup)
          in div (created by HeaderActionGroup)
          in HeaderActionGroup (created by Header)
          in header (created by Header)
          in Header (created by Header)
          in Header (created by SuiteHeader)
          in SuiteHeader

      at printWarning (../../node_modules/react-dom/cjs/react-dom.development.js:88:30)
      at error (../../node_modules/react-dom/cjs/react-dom.development.js:60:5)
      at sanitizeURL (../../node_modules/react-dom/cjs/react-dom.development.js:1171:7)
      at setValueForProperty (../../node_modules/react-dom/cjs/react-dom.development.js:1343:9)
      at setInitialDOMProperties (../../node_modules/react-dom/cjs/react-dom.development.js:5831:7)
      at setInitialProperties (../../node_modules/react-dom/cjs/react-dom.development.js:6026:3)
      at finalizeInitialChildren (../../node_modules/react-dom/cjs/react-dom.development.js:7499:3)
      at completeWork (../../node_modules/react-dom/cjs/react-dom.development.js:18978:17)
```

**Comment by davidicus** [comment]
closed by linked PR
