### ISSUE TITLE
[MenuButton] Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by kevinsperrine** [carbon-design-system/carbon-addons-iot-react#2451]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug
While cleaning up testing output we've uncovered some other bugs that may introduce breaking changes that need to be fixed in v3.
```
  ● Console

    console.error
      Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
          in ContextMenu (created by MenuButton)
          in div (created by MenuButton)
          in MenuButton

      at printWarning (../../node_modules/react-dom/cjs/react-dom.development.js:88:30)
      at error (../../node_modules/react-dom/cjs/react-dom.development.js:60:5)
      at warnAboutUpdateOnUnmountedFiberInDEV (../../node_modules/react-dom/cjs/react-dom.development.js:23161:5)
      at scheduleUpdateOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:21169:5)
      at dispatchAction (../../node_modules/react-dom/cjs/react-dom.development.js:15660:5)
      at Document.document.addEventListener.once (../../node_modules/carbon-components-react/lib/components/ContextMenu/ContextMenu.js:242:9)
      at innerInvokeEventListeners (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:330:27)
      at invokeEventListeners (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:281:3)
```

**Comment by kevinsperrine** [comment]
This is actually a bug in carbon's ContextMenu that is fixed in v10.36+.
