### ISSUE TITLE
[DateTimePicker] If you try and set a relative time range from a different hour/minute than right now (empty) it explodes

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#2463]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

To see the bug go to this story:
https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-datetime-picker--selected-relative

Pop out the relative menu:
![image](https://user-images.githubusercontent.com/6663002/124326885-74df9180-db44-11eb-88ee-0a7bf21eaa2c.png)

Now go to the hours/minutes field, clear the field and start typing.  You'll get an error:

TypeError: r.clone is not a function
    at Be (https://next.carbon-addons-iot-react.com/main.e63e0e73.iframe.bundle.js:1:1240384)
    at ze (https://next.carbon-addons-iot-react.com/main.e63e0e73.iframe.bundle.js:1:1241634)
    at https://next.carbon-addons-iot-react.com/main.e63e0e73.iframe.bundle.js:1:1241684
    at ac (https://next.carbon-addons-iot-react.com/vendors~main.523c5a52.iframe.bundle.js:139:83210)
    at vl (https://next.carbon-addons-iot-react.com/vendors~main.523c5a52.iframe.bundle.js:139:102295)
    at t.unstable_runWithPriority (https://next.carbon-addons-iot-react.com/vendors~main.523c5a52.iframe.bundle.js:147:3844)
    at Na (https://next.carbon-addons-iot-react.com/vendors~main.523c5a52.iframe.bundle.js:139:45025)
    at ml (https://next.carbon-addons-iot-react.com/vendors~main.523c5a52.iframe.bundle.js:139:102054)

Seems like it's this code here:  in parseValue of DateTimePicker
```
if (value.relative.relativeToTime) {
            endDate = endDate.hours(value.relative.relativeToTime.split(':')[0]);
            endDate = endDate.minutes(value.relative.relativeToTime.split(':')[1]);
          }
        }
        const startDate = endDate
          .clone()
```
We shouldn't be assigning to endDate

### To Reproduce

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/IBM/carbon-addons-iot-react/tree/master/examples/codesandbox

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by kevinsperrine** [comment]
Fixed by https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2467
