### ISSUE TITLE
[StatefulTable] console warnings

### ISSUE THREAD

**Issue by panpan-lin** [carbon-design-system/carbon-addons-iot-react#2950]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

When using the StatefulTable component, we saw the following console error, which originates from the [TableToolbarContent from Carbon-Components-React](https://github.com/carbon-design-system/carbon-components-react/blob/master/src/components/DataTable/TableToolbarContent.js):
```
      Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
          at div
          at TableToolbarContent (/Users/panpan/git/maximo/wi-dashboard/node_modules/carbon-components-react/lib/tools/wrapComponent.js:32:31)
          at section
          at TableToolbar (/Users/panpan/git/maximo/wi-dashboard/node_modules/carbon-components-react/lib/components/DataTable/TableToolbar.js:37:23)
          at TableToolbar (/Users/panpan/git/maximo/wi-dashboard/node_modules/carbon-addons-iot-react/lib/components/Table/TableToolbar/TableToolbar.js:167:22)
          at div
          at TableContainer (/Users/panpan/git/maximo/wi-dashboard/node_modules/carbon-components-react/lib/components/DataTable/TableContainer.js:29:24)
          at Table (/Users/panpan/git/maximo/wi-dashboard/node_modules/carbon-addons-iot-react/lib/components/Table/Table.js:530:46)
          at StatefulTable (/Users/panpan/git/maximo/wi-dashboard/node_modules/carbon-addons-iot-react/lib/components/Table/StatefulTable.js:59:26)
          at CommonTable (/Users/panpan/git/maximo/wi-dashboard/src/Common/components/CommonTable/CommonTable.jsx:61:3)
```

### To Reproduce

Use the `StatefulTable` component, and observe the browser console. Even when passing a unique key to StatefulTable or any suspected child elements didn't resolve the issue.

### Expected behavior

`StatefulTable` could be used without the console error.

### Environment/versions:
- Browser: chrome, FireFox, headless unit test
- `carbon-addons-iot-react` version: 2.146.0-next.48

**Comment by kevinsperrine** [comment]
@panpan-lin I'm trying to recreate this to track it down and fix it, but so far I haven't been able to. We're using the StatefulTable with many toolbar items in this story (https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table-statefultable--stateful-example-with-row-nesting-and-fixed-columns), but it's not showing a key error. Are you perhaps adding content using the `customToolbarContent` prop and that's where the error is originating? If not, can you make a reproduction repo for me in codesandbox? https://codesandbox.io/s/github/carbon-design-system/carbon-addons-iot-react/tree/next/packages/react/examples/codesandbox

**Comment by panpan-lin** [comment]
@kevinsperrine Sorry for taking so long to get back! We did add content using the `customToolbarContent` prop. So I suppose it is possible that the key error could be coming from that.

**Comment by kevinsperrine** [comment]
Thanks, @panpan-lin. I'll close this out now, but if you do find it's coming from within this library, please let me know and we'll get it straightened out.
